name: Build and Deploy to Cloudflare Pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build:basic-react

    - name: Deploy to Cloudflare Pages
      run: yarn deploy:basic-react
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
